### ISSUE TITLE
query return "71 Protocol error" after "11 Resource temporarily unavailable"

### ISSUE THREAD

**Issue by bigml** [algernon/libmongo-client#18]
I'm using mongodb without replset mode(single server).

Query ok on mongod running ok.

The same query will return "11 Resource temporarily unavailable" after I run db.fsyncLock() to the mongod server. There is no problem.

But after I turn the server run normally(db.fsyncUnlock()), The following same query will return "71 Protocol error".

After debug, I notice that this is because  (h.resp_to != rid) in _mongo_sync_packet_recv().

algernon, can you fix it?

**Comment by algernon** [comment]
Seeing as the library is obsolete, unmaintained, and not developed further anymore, I'm closing this issue.
