### ISSUE TITLE
Last error stored in connection structure may interfere with subsequent requests

### ISSUE THREAD

**Issue by bamirov** [algernon/libmongo-client#31]
1) [_mongo_sync_cmd_verify_result] determines the success of it's execution based on the return value of the function [_mongo_sync_cmd_verify_result] and the value of variable [error], assigned by the same function.

---

mongo-sync.c, Lines 810-812

static inline gboolean
_mongo_sync_cmd_verify_result (mongo_sync_connection *conn,
                               const gchar *ns)
{
...
  res = mongo_sync_cmd_get_last_error (conn, db, &error);
...
  res = res && ((error) ? FALSE : TRUE);
 ...
  return res;
}

---

2) However, there is an execution path in function [mongo_sync_cmd_get_last_error] that sets the value if error to the previous error, which is stored in [conn]. This logic triggers when function [_mongo_sync_get_error] sets the value of [error] to NULL.

---

mongo-sync.c, Lines 1381-1382

gboolean
mongo_sync_cmd_get_last_error (mongo_sync_connection _conn,
                               const gchar *db, gchar *_error) {
if (!_mongo_sync_get_error (cmd, error))
    { ... }
...
  if (*error == NULL)
    *error = g_strdup (conn->last_error);
}

---

3) [_mongo_sync_get_error], in it's turn, sets the value of [error] to NULL pretty much after every successful execution. That results in [_mongo_sync_cmd_verify_result] erroneously returning "FALSE" for successful requests.

---

mongo-sync.c, Lines 726-728

static gboolean
_mongo_sync_get_error (const bson _rep, gchar *_error)
{
...
  if (bson_cursor_type (c) == BSON_TYPE_NONE ||
      bson_cursor_type (c) == BSON_TYPE_NULL)
    {
      *error = NULL;
      bson_cursor_free (c);
      return TRUE;
    }
 ...
}

---

Fix proposal: reset [conn.last_error] on successful requests instead of copying last error from connection to [error] variable.

**Comment by algernon** [comment]
As this library is obsolete, and no development is being done, I'm closing this issue.
