### ISSUE TITLE
Build error with gcc-5

### ISSUE THREAD

**Issue by JoergFF** [algernon/libmongo-client#37]
Hi,

Debian change the compiler to gcc-5.

With this compiler one test fails:

[quote]
unit/bson/bson_cursor_new ............................................... ok
unit/bson/bson_find ..................................................... ok
unit/bson/bson_cursor_next .............................................. ok
unit/bson/bson_cursor_find_next ......................................... ok
#   Failed test 'bson_cursor_find() should wrap over if neccessary'
#   at ../../tests/unit/bson/bson_cursor_find.c line 24.
unit/bson/bson_cursor_find .............................................. 
Failed 1/7 subtests 
unit/bson/bson_cursor_type .............................................. ok
unit/bson/bson_cursor_type_as_string .................................... ok
unit/bson/bson_cursor_key ............................................... ok
unit/bson/bson_cursor_get_string ........................................ ok
unit/bson/bson_cursor_get_double ........................................ ok
[...]
perf/bson/p_bson_find ................................................... ok

Test Summary Report
-------------------
unit/bson/bson_cursor_find                                            (Wstat: 0 Tests: 7 Failed: 1)
  Failed test:  4
Files=153, Tests=1033,  4 wallclock secs ( 0.40 usr  0.26 sys +  0.58 cusr  0.02 csys =  1.26 CPU)
Result: FAIL
[/quote]

CU
Jörg

**Comment by algernon** [comment]
This has been fixed already, see #36. The Debian package needs to be updated, mind you, to include the fix.
